### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ghost** [sambody/inkscape-guide-tools#2]
Thanks for this plugin it is greatly needed. 

3 other ideas coming from al older plugin is the divide by third, the golden ratio division and the diagonal guide creation. I whish I could help created that ;)

**Comment by sambody** [comment]
Sorry for my late reply. Thanks for your comment, @damarusama. What do you mean by diagonal guide creation?

**Comment by sambody** [comment]
Your ideas are already part of any default Inkscape installation, as part of the "old" plugin Guide Creator (Extensions - Generate). So I don't think I am going to duplicate that functionality.
